export { default as About } from './About/About';
export { default as Cargador } from './Cargador/Cargador';
export { default as Footer } from './Footer/Footer';
export { default as Hero } from './Hero/Hero';
export * from './Icons';
export { default as NavbarMobile } from './NavbarMobile/NavbarMobile';
export { default as NavbarPC } from './NavbarPC/NavbarPC';
export { default as Proyectos } from './Proyectos/Proyectos';
export { default as Robot } from './Robot';
export * from './index';
