
import './globals.css'
import { Footer, NavbarPC } from './components'

export const metadata = {
  title: 'Portafolio Guillermo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NavbarPC />
        {children}
        <Footer />
      </body>
    </html>
  )
}
